admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation
