# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        users:
            entity:
                class: AppBundle\Entity\User
    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern: "^/"
            provider: users
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: homepage
#                always_use_default_target_path: true
            logout:
                path: logout
                target: homepage
#            switch_user: ~
    access_control:
        - { path: "^/login$", roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: "^/", roles: [ROLE_USER] }
        - { path: "^/admin", roles: [ROLE_ADMIN] }