# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    myuser:
                        password: '$2y$13$kRdK7hG5b4PcrgcgYPnWyeiB/NzjcfR6vWyiUZPe9MvJlZQBnm9jS'
                        roles: 'ROLE_USER'
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
#        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: "^/"
            http_basic: ~
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: homepage
#            switch_user: ~
    access_control:
        - { path: "^/login$", roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: "^/", roles: [ROLE_USER] }